### ISSUE TITLE
QRangeSlider is not displayed correctly

### ISSUE THREAD

**Issue by pascalzeugin** [napari/superqt#129] opened 2022-10-17 08:23 UTC
**Description**
When enabling a stylesheet (https://pypi.org/project/pyqtdarktheme/) the QRangeSlider and all its derivatives are not rendered/displayed correctly.

**To Reproduce**
1. Install pyqtdarktheme version 1.1.0
2. Install qtpy
3. Install superqt
4. Execute minimal example

```
from qtpy.QtCore import Qt
from qtpy.QtWidgets import QApplication
from superqt import QRangeSlider
import qdarktheme

app = QApplication([])
app.setStyleSheet(qdarktheme.load_stylesheet())
slider = QRangeSlider(Qt.Orientation.Horizontal)
slider.setValue((20, 80))
slider.show()

app.exec_()
```

**Expected behavior**
Correct rendering of the widget

**Desktop (please complete the following information):**
 - Win10
 - PyQt5
 - Python 3.9
![2022-10-17 10_22_53-Window](https://user-images.githubusercontent.com/72567950/196126357-3c9748b2-bb2e-43da-b1ad-2dbe1d3a5fbc.png)

**Comment by tlambert03** [comment] 2022-10-17 11:58
yes, sorry this is a known issue, and a duplicate of issue #58 

to keep things in one place, i'm going to close this issue and refer others to that one

**Closed by tlambert03** 2022-10-17 11:58 UTC
